export const people = [
  { id: 1, status: "notavailable" },
  { id: 2, status: "notavailable" },
  { id: 3, status: "notavailable" },
  { id: 4, status: "notavailable" },
  { id: 5, status: "notavailable" },
  { id: 6, status: "notavailable" },
  { id: 7, status: "notavailable" },
  { id: 8, status: "notavailable" },
  { id: 9, status: "notavailable" },
  { id: 10, status: "notavailable" },
  { id: 11, status: "notavailable" },
  { id: 12, status: "notavailable" },
  { id: 13, status: "notavailable" },
  { id: 14, status: "notavailable" },
  { id: 15, status: "notavailable" },
  { id: 16, status: "notavailable" },
];
export const button = [
  { id: "1", selected: false },
  { id: "2", selected: false },
  { id: "3", selected: false },
  { id: "4", selected: false },
  { id: "5", selected: false },
  { id: "6", selected: false },
  { id: "7", selected: false },
  { id: "8", selected: false },
  { id: "9", selected: false },
  { id: "10", selected: false },
];
